export enum ERole {
    ROLE_ADMIN = 'ROLE_ADMIN',
    ROLE_USER = 'ROLE_USER',
    ROLE_HRE = 'ROLE_HRE',
    ROLE_HR_ADMIN = 'ROLE_HR_ADMIN',
    ROLE_CRME = 'ROLE_CRME',
    ROLE_CRM_ADMIN = 'ROLE_CRM_ADMIN',
    ROLE_PROJECT = 'ROLE_PROJECT',
    ROLE_PROJECT_ADMIN = 'ROLE_PROJECT_ADMIN',
    ROLE_PRODUCT = 'ROLE_PRODUCT',
    ROLE_PRODUCT_ADMIN = 'ROLE_PRODUCT_ADMIN'
  }
  